outputs:
  - name: "print_sch"
    comment: "PDF - print schematic"
    type: pdf_sch_print
    dir: "Fabrication/PDFs"

  - name: "print_front"
    comment: "PDF - front copper and user drawings"
    type: pdf_pcb_print
    dir: "Fabrication/PDFs"
    layers:
      - layer: F.Cu
      - layer: Dwgs.User

  - name: "print_bottom"
    comment: "PDF - back copper and user drawings"
    type: pdf_pcb_print
    dir: "Fabrication/PDFs"
    layers:
      - layer: B.Cu
      - layer: Dwgs.User

  - name: "interactive_bom"
    comment: "Interactive Bill of Materials"
    type: ibom
    dir: "Fabrication/BOM"
    options:
      blacklist: "DNF*"

  - name: pcb_top_w
    comment: "Renders - top (white)"
    type: pcbdraw
    dir: "Fabrication/Renders"
    options:
      format: jpg
      style: set-white-enig
      show_components: none
      dpi: 600

  - name: pcb_bot_w
    comment: "Renders - bottom (white)"
    type: pcbdraw
    dir: "Fabrication/Renders"
    options:
      format: jpg
      style: set-white-enig
      bottom: True
      show_components: none
      dpi: 600

  - name: step
    comment: "Renders - 3D model (STEP)"
    type: step
    dir: "Fabrication/Renders"
    options:
      metric_units: true
      origin: 85,66.2
